### ISSUE TITLE
Positioning the popup

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [andrewRosenblum/AJRNutritionController#1]
Hi Andrew, thanks for the cool control. I'm planning to use it in one of my apps. However I'd like to make it appear centered in the screen because when there's a navigation bar, the popup appears under it.

![screen shot 2014-01-27 at 9 45 12 pm](https://f.cloud.github.com/assets/2551877/2010469/473bdffe-876e-11e3-87b8-9cda312ad67f.png)

How can I define the position for the popup?

Thank you.

**Comment by Isuru-Nanayakkara** [comment]
Okay, I resolved the issue myself :) Just did some modification to your code.

Inside presentInParentViewController method, before adding the view to the parent view, I defined a new position for it. Like so,

```
CGRect viewFrame = self.view.frame;
viewFrame.origin.y += 70;
self.view.frame = viewFrame;

[parentViewController.view addSubview:self.view];
```

All good now :+1: 

![screen shot 2014-01-27 at 9 55 42 pm](https://f.cloud.github.com/assets/2551877/2010571/b6a69e28-876f-11e3-8e0a-c4337dd7222e.png)

**Comment by andrewRosenblum** [comment]
Ok great.  Glad you got this resolved.  If you think about it, shoot me a link to your finished app so I can see it in action.

**Comment by Isuru-Nanayakkara** [comment]
Will do :)

**Comment by Isuru-Nanayakkara** [comment]
Hey @andrewRosenblum 

I seem to have hit a snag when using my way of repositioning the view in a UITableView. 2 problems arise when using this with a table view.

1). Since I have hardcoded the value from the top to display the view, when I scroll down it still appears in the same position. 

2). The background dimming only applies to the visible portion of the table view. If I scroll down, the rest of the screen isn't dimmed.

I have uploaded a xcode project with these issues if you want to take a look at to understand better. Can you please tell me how to correct these issues? I'd really appreciate it.
https://www.dropbox.com/s/6tvcxcp6i7zlrt4/NutritionViewControllerTest.zip

Thank you
